// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  room: dynamic(() => import("./Room")),
  rooms: dynamic(() => import("./Rooms")),
  text_block: dynamic(() => import("./TextBlock")),
  video: dynamic(() => import("./Video")),
};
