// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer: dynamic(() => import("./Footer")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  image_text: dynamic(() => import("./ImageText")),
  map: dynamic(() => import("./Map")),
  room: dynamic(() => import("./Room")),
  rooms: dynamic(() => import("./Rooms")),
  video: dynamic(() => import("./Video")),
};
